version: "3.9"
services:
  app:
    container_name: git-namer
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "5100:3000"
    image: t3-app
    restart: always
